import SwiftUI
import MeldShared

/// Bridges the Kotlin-provided `UIViewController` (Compose content) into SwiftUI.
/// The facade name `MainViewControllerKt` is generated by Kotlin/Native from
/// `shared/src/iosMain/.../MainViewController.kt`; CI greps it in `MeldShared.h`.
struct ComposeViewController: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        MainViewControllerKt.mainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
    }
}

struct ContentView: View {
    var body: some View {
        ComposeViewController()
            .ignoresSafeArea()
    }
}
